FROM node:23

WORKDIR /app

# Copia o package.json e instala as dependências
COPY package*.json ./
# RUN npm install

# # Instala o Vue CLI
# RUN npm install -g @vue/cli


EXPOSE 8080

CMD ["tail", "-f", "/dev/null"]

