version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-php
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8080:80"  # Porta do Apache
      - "9003:9003"  # Porta do Xdebug
    depends_on:
      - mysql 

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8081:8080" 
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run serve

volumes:
  mysql-data:
